### ISSUE TITLE
bin field of BAM record does not equal value computed

### ISSUE THREAD

**Issue by arnaos** [seqan/seqan#1046]
Hi,

I am running Picard tools on a file generated with the SeqAn bam_io module (see below). On the original file, Picard tools works fine, but the Seqan generated file leads to an error message.

Here is the Picard command I used:
`$ java -Xmx7g -XX:+UseConcMarkSweepGC -jar ../picard-tools-1.117/MarkDuplicates.jar \
METRICS_FILE=test_bamfile.writingInSeqan.md.bam.metrics \
TMP_DIR=/tmp/writingInSeqan \
INPUT=test_bamfile.writingInSeqan.bam \
OUTPUT=test_bamfile.writingInSeqan.md.bam \
READ_NAME_REGEX='[a-zA-Z0-9-]+:[0-9]+:[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+)'`

And the full error message:
```
[Fri Jul 24 10:29:47 GMT 2015] picard.sam.MarkDuplicates INPUT=[test_bamfile.writingInSeqan.bam] OUTPUT=test_bamfile.writingInSeqan.md.bam METRICS_FILE=test_bamfile.writingInSeqan.md.bam.metrics READ_NAME_REGEX=[a-zA-Z0-9-]+:[0-9]+:[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+) TMP_DIR=[/tmp/writingInSeqan]    PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates REMOVE_DUPLICATES=false ASSUME_SORTED=false MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Fri Jul 24 10:29:47 GMT 2015] Executing as ... on Linux ...; Picard version: 1.117(107391d3f3e72b31589868c250262ca79659f577_1405353489) JdkDeflater
INFO    2015-07-24 10:29:47     MarkDuplicates  Start of doWork freeMemory: 1013032000; totalMemory: 1019609088; maxMemory: 7402815488
INFO    2015-07-24 10:29:47     MarkDuplicates  Reading input file and constructing read end information.
INFO    2015-07-24 10:29:47     MarkDuplicates  Will retain up to 29376251 data points before spilling to disk.
[Fri Jul 24 10:29:50 GMT 2015] picard.sam.MarkDuplicates done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=1019609088
To get help, see http://picard.sourceforge.net/index.shtml#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 5, Read name ST-E00183:44:H0DGBALXX:2:1101:29024:18397, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:452)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:643)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:628)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:598)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:514)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:488)
        at picard.sam.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:413)
        at picard.sam.MarkDuplicates.doWork(MarkDuplicates.java:177)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:183)
        at picard.sam.MarkDuplicates.main(MarkDuplicates.java:161)
```

The interesting line is the one starting with `Exception in thread...`.

Have you seen this error before and can you suggest a solution?

\Arna

--
A simplified version of my program where the error occurs:
```C++
#include <seqan/bam_io.h>

using namespace seqan;

int main(int argc, char const ** argv)
{

    if (argc < 2)
    {
        std::cerr << "USAGE: " << argv[0] << " INPUT.bam [OUTPUT.bam]" << "\n";
        return 1;
    }

    BamFileIn bamFileIn;
    if (!open(bamFileIn, argv[1]))
    {
        std::cerr << "ERROR: Could not open file" << argv[1] << std::endl;
        return 1;
    }

    seqan::BamFileOut bamFileOut(context(bamFileIn), argv[2]);

    try
    {
        // Copy header.
        BamHeader header;
        readHeader(header, bamFileIn);
        writeHeader(bamFileOut, header);

        // Copy records.
        BamAlignmentRecord record;
        while (!atEnd(bamFileIn))
        {
            readRecord(record, bamFileIn);
            writeRecord(bamFileOut, record);
        }
    }
    catch (Exception const & e)
    {
        std::cout << "ERROR: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}
```

**Comment by esiragusa** [comment]
@arnaos thanks for reporting this issue. PR #1064 should have fixed it. Would you please update to the latest master and let me know if the problem persists?

**Comment by arnaos** [comment]
I have updated to the newest master and tested it on a full sized bam file. The problem is now fixed.

Thank you,

Arna

________________________________
