### ISSUE TITLE
Fix KNIME T-Coffee node

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#2369]
It seems the t-coffe node in KNIME is broken:

```console
2018-12-07 15:35:31,554 : DEBUG : KNIME-Worker-7 : NodeContainer : SeqanTcoffee : 2:1 : SeqanTcoffee 2:1 has new state: EXECUTING
2018-12-07 15:35:31,554 : DEBUG : KNIME-Worker-7 : WorkflowFileStoreHandlerRepository : SeqanTcoffee : 2:1 : Adding handler be879f55-65c0-4e80-acc8-9cefce3d7cd3 (SeqanTcoffee 2:1: <no directory>) - 3 in total
2018-12-07 15:35:31,554 : DEBUG : KNIME-Worker-7 : LocalNodeExecutionJob : SeqanTcoffee : 2:1 : SeqanTcoffee 2:1 Start execute
2018-12-07 15:35:31,554 : DEBUG : KNIME-WFM-Parent-Notifier : NodeContainer :  :  : ROOT  has new state: EXECUTING
2018-12-07 15:35:31,557 : DEBUG : KNIME-Worker-7 : WriteFileStoreHandler : SeqanTcoffee : 2:1 : Assigning temp directory to file store "be879f55-65c0-4e80-acc8-9cefce3d7cd3 (SeqanTcoffee 2:1: /tmp/knime_Workflow Manage41149/knime_fs-SeqanTcoffee_2_1-41154)"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-MZIDENTML" for file extension "mzid"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-MZIDENTML" for file extension "mzidentml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-MASCOTDAT" for file extension "dat"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-MAGELLANSTORAGEFILE" for file extension "msf"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-TANDEMXML" for file extension "tandem.xml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-TANDEMXML" for file extension "t.xml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-TANDEMXML" for file extension "xml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-IDXML" for file extension "idxml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-PIAXML" for file extension "pia.xml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "text/CSV" for file extension "csv"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-MZTAB" for file extension "mztab"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-dta" for file extension "dta"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-dta2d" for file extension "dta2d"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mzdata" for file extension "mzdata"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mzxml" for file extension "mzxml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-featurexml" for file extension "featurexml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-idxml" for file extension "idxml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-consensusxml" for file extension "consensusxml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mgf" for file extension "mgf"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-ini" for file extension "ini"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-toppas" for file extension "toppas"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-transformationxml" for file extension "trafoxml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mzml" for file extension "mzml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-ms2" for file extension "ms2"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-pepxml" for file extension "pepxml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-protxml" for file extension "protxml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mzidentml" for file extension "mzid"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-gelml" for file extension "gelml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-traml" for file extension "traml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-msp" for file extension "msp"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-omssaxml" for file extension "xml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mascotxml" for file extension "xml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "image/png" for file extension "png"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-xmass" for file extension "fid"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "text/tsv" for file extension "tsv"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "text/csv" for file extension "csv"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mrm" for file extension "mrm"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-peplist" for file extension "peplist"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-hardkloer" for file extension "hardkloer"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-kroenik" for file extension "kroenik"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fasta"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fa"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-edta" for file extension "edta"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-psq" for file extension "psq"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-exe" for file extension "exe"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mzquantml" for file extension "mzq"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-qcml" for file extension "qcml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mztab" for file extension "mztab"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-paramxml" for file extension "paramxml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mzml" for file extension "mzml"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-mztab" for file extension "mztab"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fa"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fa.bgzf"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fa.gz"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fa.bz2"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fasta"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fasta.bgzf"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fasta.gz"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fasta.bz2"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "faa"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "faa.bgzf"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "faa.gz"
2018-12-07 15:35:31,562 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "faa.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "ffn"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "ffn.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "ffn.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "ffn.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fna"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fna.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fna.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fna.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "frn"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "frn.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "frn.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "frn.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "embl"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "embl.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "embl.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "embl.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "gbk"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "gbk.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "gbk.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "gbk.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "raw"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "raw.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "raw.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "raw.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fq"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fq.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fq.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fq.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fastq"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fastq.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fastq.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fastq.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-masic" for file extension "masic"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-masic" for file extension "mas"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-gsi" for file extension "gsi"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-z-gsi" for file extension "gsi.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-gff" for file extension "gff"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-gtf" for file extension "gtf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-razers" for file extension "razers"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-eland" for file extension "eland"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-sam" for file extension "sam"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-sam" for file extension "sam.bgzf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-sam" for file extension "sam.gz"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-sam" for file extension "sam.bz2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bam" for file extension "bam"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-afg" for file extension "afg"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-dist" for file extension "dist"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-dot" for file extension "dot"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-newick" for file extension "newick"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-alftsv" for file extension "alf.tsv"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-txt" for file extension "txt"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-txt" for file extension "csv"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-txt" for file extension "tsv"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-txt" for file extension "tab"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-txt" for file extension "log"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bam-coverage-tsv" for file extension "bam_coverage_tsv"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fq-stats-tsv" for file extension "fq_stats_tsv"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-rabema-report-tsv" for file extension "rabema_report_tsv"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "lf.drp"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "lf.drs"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "lf.drv"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "lf.pst"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "sa.ind"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "sa.len"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "sa.val"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "txt.concat"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "txt.limits"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-index" for file extension "txt.size"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-yara" for file extension "rid.concat"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-yara" for file extension "rid.limits"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-vcf" for file extension "vcf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bed" for file extension "bed"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bed" for file extension "bigbed"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bed" for file extension "bedgraph"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-misc" for file extension "r"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fa"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fasta" for file extension "fasta"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fq"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-fastq" for file extension "fastq"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-sam" for file extension "sam"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bam" for file extension "bam"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bowtie-index" for file extension "ebwt"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bowtie2-index" for file extension "bt2"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bcf" for file extension "bcf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-vcf" for file extension "vcf"
2018-12-07 15:35:31,563 : DEBUG : KNIME-Worker-7 : MIMEMap : SeqanTcoffee : 2:1 : Found MIME-Type "application/x-bwa-index" for file extension "bwaidx"
2018-12-07 15:35:31,564 : DEBUG : KNIME-Worker-7 : GenericKnimeNodeModel : SeqanTcoffee : 2:1 : > setting param seqan_tcoffee.outfile->/tmp/knime_Workflow Manage41149/knime_fs-SeqanTcoffee_2_1-41154/000/000/SeqanTcoffee_0/sequence.fa
2018-12-07 15:35:31,568 : DEBUG : KNIME-Worker-7 : Node : SeqanTcoffee : 2:1 : reset
2018-12-07 15:35:31,568 : ERROR : KNIME-Worker-7 : Node : SeqanTcoffee : 2:1 : Execute failed: ("NullPointerException"): null
2018-12-07 15:35:31,568 : DEBUG : KNIME-Worker-7 : Node : SeqanTcoffee : 2:1 : Execute failed: ("NullPointerException"): null
java.lang.NullPointerException
    at com.genericworkflownodes.knime.parameter.StringListParameter.getStrings(StringListParameter.java:148)
    at com.genericworkflownodes.knime.config.PlainNodeConfigurationWriter.write(PlainNodeConfigurationWriter.java:51)
    at com.genericworkflownodes.knime.execution.impl.CLICommandGenerator.exportPlainConfiguration(CLICommandGenerator.java:301)
    at com.genericworkflownodes.knime.execution.impl.CLICommandGenerator.generateCommands(CLICommandGenerator.java:71)
    at com.genericworkflownodes.knime.execution.impl.LocalToolExecutor.prepareExecution(LocalToolExecutor.java:405)
    at com.genericworkflownodes.knime.generic_node.GenericKnimeNodeModel.prepareExecutor(GenericKnimeNodeModel.java:557)
    at com.genericworkflownodes.knime.generic_node.GenericKnimeNodeModel.execute(GenericKnimeNodeModel.java:510)
    at org.knime.core.node.NodeModel.executeModel(NodeModel.java:567)
    at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1173)
    at org.knime.core.node.Node.execute(Node.java:960)
    at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:561)
    at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
    at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
    at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
    at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
    at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
    at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
```

2 days

Fixed by https://github.com/genericworkflownodes/GenericKnimeNodes/pull/238

**Comment by rrahn** [comment]
See https://github.com/genericworkflownodes/GenericKnimeNodes/issues/237
