### ISSUE TITLE
Error occured while running mason simulator

### ISSUE THREAD

**Issue by sahilrishav2** [seqan/seqan#2517]
Hello,

I need urgent help from your side. Actually, I am using a tool Ditasic (that uses mason simulator) for processing my 850 fasta sequence files. But it is showing some error:

```
Traceback (most recent call last):
  File "/home4_jbod/rishav1/miniconda3/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home4_jbod/rishav1/miniconda3/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/jbod_new/home4_jbod/rishav1/Ditasic/ditasic_matrix.py", line 17, in parallelSimulate
    ditasic_utils.run_simulator["mason_illumina"](ref, sim, length, ref_probs, number)
  File "/jbod_new/home4_jbod/rishav1/Ditasic/core/ditasic_utils.py", line 96, in run_mason_illumina
    subprocess.check_call(command, stderr=subprocess.STDOUT, shell=True)
  File "/home4_jbod/rishav1/miniconda3/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mason_simulator -n 1000 --illumina-read-length 100 --illumina-prob-mismatch 0.004 --illumina-prob-mismatch-begin 0.002 --illumina-prob-mismatch-end 0.012 --fragment-size-model normal --fragment-mean-size 200 --fragment-size-std-dev 20 -ir '/home4_jbod/rishav1/plant_bacterial_genome/P.syringae/GCA_000145925.1_ASM14592v1_genomic.fasta' -o './temp/GCA_000145925.1_ASM14592v1_genomic.fasta.fastq'' died with <Signals.SIGABRT: 6>.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/jbod_new/home4_jbod/rishav1/Ditasic/ditasic_matrix.py", line 128, in <module>
    p.map_async(parallelSimulate, arglist).get(9999999)
  File "/home4_jbod/rishav1/miniconda3/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
subprocess.CalledProcessError: Command 'mason_simulator -n 1000 --illumina-read-length 100 --illumina-prob-mismatch 0.004 --illumina-prob-mismatch-begin 0.002 --illumina-prob-mismatch-end 0.012 --fragment-size-model normal --fragment-mean-size 200 --fragment-size-std-dev 20 -ir '/home4_jbod/rishav1/plant_bacterial_genome/P.syringae/GCA_000145925.1_ASM14592v1_genomic.fasta' -o './temp/GCA_000145925.1_ASM14592v1_genomic.fasta.fastq'' died with <Signals.SIGABRT: 6>.

```

Kindly help me regarding this.

Thank You

**Comment by sahilrishav2** [comment]
Thank you for your time. I solved the error by reducing the number of reads. Due to the large number of reads, memory got full during processing and hence got interrupted.
